/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Clientes;

import javax.swing.JOptionPane;

/**
 *
 * @author pedro
 */
public class CadastroClientes extends javax.swing.JPanel {

    /**
     * Creates new form CadastroClientes
     */
    public CadastroClientes() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        NomeClienteLabel = new javax.swing.JLabel();
        NomeCliente = new javax.swing.JTextField();
        TelefoneClienteLabel = new javax.swing.JLabel();
        CEPClienteLabel = new javax.swing.JLabel();
        BairroCliente = new javax.swing.JTextField();
        BairroClienteLabel = new javax.swing.JLabel();
        NumeroCliente = new javax.swing.JTextField();
        NumeroClienteLabel = new javax.swing.JLabel();
        EnderecoCliente = new javax.swing.JTextField();
        EnderecoClienteLabel = new javax.swing.JLabel();
        UFCliente = new javax.swing.JTextField();
        UFCLienteLabel = new javax.swing.JLabel();
        CadastrarBtn = new javax.swing.JButton();
        CancelarBtn = new javax.swing.JButton();
        CEPCliente = new javax.swing.JFormattedTextField();
        TelefoneCliente = new javax.swing.JFormattedTextField();
        CidadeCliente = new javax.swing.JTextField();
        CidadeClienteLabel = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(12, 12, 12));
        jLabel1.setText("Cadastro Cliente");
        jLabel1.setToolTipText("Entrada de Produtos");

        NomeClienteLabel.setForeground(new java.awt.Color(12, 12, 12));
        NomeClienteLabel.setText("Nome do Cliente");

        NomeCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NomeClienteActionPerformed(evt);
            }
        });
        NomeCliente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                NomeClienteKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                NomeClienteKeyTyped(evt);
            }
        });

        TelefoneClienteLabel.setForeground(new java.awt.Color(12, 12, 12));
        TelefoneClienteLabel.setText("Telefone");

        CEPClienteLabel.setForeground(new java.awt.Color(12, 12, 12));
        CEPClienteLabel.setText("CEP");

        BairroCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BairroClienteActionPerformed(evt);
            }
        });
        BairroCliente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                BairroClienteKeyPressed(evt);
            }
        });

        BairroClienteLabel.setForeground(new java.awt.Color(12, 12, 12));
        BairroClienteLabel.setText("Bairro");

        NumeroCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NumeroClienteActionPerformed(evt);
            }
        });
        NumeroCliente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                NumeroClienteKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                NumeroClienteKeyTyped(evt);
            }
        });

        NumeroClienteLabel.setForeground(new java.awt.Color(12, 12, 12));
        NumeroClienteLabel.setText("Numero");

        EnderecoCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EnderecoClienteActionPerformed(evt);
            }
        });
        EnderecoCliente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                EnderecoClienteKeyPressed(evt);
            }
        });

        EnderecoClienteLabel.setForeground(new java.awt.Color(12, 12, 12));
        EnderecoClienteLabel.setText("Endereço");

        UFCliente.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                UFClienteInputMethodTextChanged(evt);
            }
        });
        UFCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UFClienteActionPerformed(evt);
            }
        });
        UFCliente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                UFClienteKeyTyped(evt);
            }
        });

        UFCLienteLabel.setForeground(new java.awt.Color(12, 12, 12));
        UFCLienteLabel.setText("UF");

        CadastrarBtn.setText("Cadastrar Cliente");
        CadastrarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CadastrarBtnActionPerformed(evt);
            }
        });

        CancelarBtn.setText("Cancelar");
        CancelarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelarBtnActionPerformed(evt);
            }
        });

        try {
            CEPCliente.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#####-###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        CEPCliente.setToolTipText("");
        CEPCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CEPClienteActionPerformed(evt);
            }
        });
        CEPCliente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                CEPClienteKeyPressed(evt);
            }
        });

        try {
            TelefoneCliente.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) #####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        TelefoneCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TelefoneClienteActionPerformed(evt);
            }
        });
        TelefoneCliente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TelefoneClienteKeyPressed(evt);
            }
        });

        CidadeCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CidadeClienteActionPerformed(evt);
            }
        });
        CidadeCliente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                CidadeClienteKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                CidadeClienteKeyTyped(evt);
            }
        });

        CidadeClienteLabel.setForeground(new java.awt.Color(12, 12, 12));
        CidadeClienteLabel.setText("Cidade");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(EnderecoClienteLabel)
                                    .addComponent(CEPClienteLabel)
                                    .addComponent(EnderecoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(CEPCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(NumeroClienteLabel)
                                    .addComponent(NumeroCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(23, 23, 23)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(UFCLienteLabel)
                                    .addComponent(UFCliente, javax.swing.GroupLayout.DEFAULT_SIZE, 467, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(BairroClienteLabel)
                                    .addComponent(BairroCliente))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(CidadeClienteLabel)
                                        .addGap(37, 37, 37))
                                    .addComponent(CidadeCliente)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(NomeClienteLabel)
                                .addGap(69, 69, 69))
                            .addComponent(NomeCliente))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TelefoneClienteLabel)
                            .addComponent(TelefoneCliente)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(CadastrarBtn)
                                .addGap(18, 18, 18)
                                .addComponent(CancelarBtn)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(38, 38, 38))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(NomeClienteLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(NomeCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(TelefoneClienteLabel)
                        .addGap(28, 28, 28))
                    .addComponent(TelefoneCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(CEPClienteLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(CEPCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(BairroClienteLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(BairroCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(CidadeClienteLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(CidadeCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(EnderecoClienteLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(EnderecoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(UFCLienteLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(UFCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(NumeroClienteLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(NumeroCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CadastrarBtn)
                    .addComponent(CancelarBtn))
                .addContainerGap(414, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void NomeClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NomeClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NomeClienteActionPerformed

    private void NomeClienteKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_NomeClienteKeyPressed
        // TODO add your handling code here:
        if(evt.getExtendedKeyCode() == evt.VK_ENTER){
            TelefoneCliente.requestFocus();
        }
    }//GEN-LAST:event_NomeClienteKeyPressed

    private void NomeClienteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_NomeClienteKeyTyped
        // TODO add your handling code here:
        char keyPress = evt.getKeyChar();
        if(!Character.isAlphabetic(keyPress) && keyPress != ' '){
            evt.consume();
        }

    }//GEN-LAST:event_NomeClienteKeyTyped

    private void BairroClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BairroClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BairroClienteActionPerformed

    private void BairroClienteKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BairroClienteKeyPressed
        // TODO add your handling code here:
        if(evt.getExtendedKeyCode() == evt.VK_ENTER){
            CidadeCliente.requestFocus();
        }
    }//GEN-LAST:event_BairroClienteKeyPressed

    private void NumeroClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NumeroClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NumeroClienteActionPerformed

    private void NumeroClienteKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_NumeroClienteKeyPressed
        // TODO add your handling code here:
        if(evt.getExtendedKeyCode() == evt.VK_ENTER){
            UFCliente.requestFocus();
        }
    }//GEN-LAST:event_NumeroClienteKeyPressed

    private void NumeroClienteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_NumeroClienteKeyTyped
        // TODO add your handling code here:

        char keyPress = evt.getKeyChar();
        if(!Character.isDigit(keyPress)){
            evt.consume();
        }
    }//GEN-LAST:event_NumeroClienteKeyTyped

    private void EnderecoClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EnderecoClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EnderecoClienteActionPerformed

    private void EnderecoClienteKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_EnderecoClienteKeyPressed
        if(evt.getExtendedKeyCode() == evt.VK_ENTER){
            NumeroCliente.requestFocus();
        }
    }//GEN-LAST:event_EnderecoClienteKeyPressed

    private void UFClienteInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_UFClienteInputMethodTextChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_UFClienteInputMethodTextChanged

    private void UFClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UFClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UFClienteActionPerformed

    private void UFClienteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_UFClienteKeyTyped
        // TODO add your handling code here
        char keyPress = evt.getKeyChar();
        String InputText = UFCliente.getText();
        UFCliente.setText(InputText.toUpperCase());
        int TamanhoInput = InputText.length();
        if(!Character.isAlphabetic(keyPress)){
            evt.consume();
        }

        if(TamanhoInput >= 2){
            evt.consume();
        }
    }//GEN-LAST:event_UFClienteKeyTyped

    private void CadastrarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CadastrarBtnActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Cadastro do Cliente efetuado:"+ "\n" +
            "Nome: " + NomeCliente.getText() + "\n" +
            "Telefone: " + TelefoneCliente.getText() + "\n" +
            "CEP: " + CEPCliente.getText() + "\n" +
            "Bairro: " + BairroCliente.getText() + "\n" +
            "Rua: " + EnderecoCliente.getText() + "\n" +
            "Numero: " + EnderecoCliente.getText() + "\n" +
            "Cidade: " + CidadeCliente.getText() + "\n" +
            "UF: " + UFCliente.getText());
    }//GEN-LAST:event_CadastrarBtnActionPerformed

    private void CancelarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelarBtnActionPerformed
        // TODO add your handling code here:
        String[] options = {"Sim", "Cancelar"};
        int resposta = JOptionPane.showOptionDialog(
            this,
            "Esta ação apagará todos os campos, tem certeza?",
            "Confirmação",
            JOptionPane.DEFAULT_OPTION,
            JOptionPane.WARNING_MESSAGE,
            null,
            options,
            options[0]
        );
        if (resposta == 0) {
            
        } else {
            CancelarBtn.requestFocus();
        }
    }//GEN-LAST:event_CancelarBtnActionPerformed

    private void CEPClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CEPClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CEPClienteActionPerformed

    private void CEPClienteKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CEPClienteKeyPressed
        // TODO add your handling code here:
        if(evt.getExtendedKeyCode() == evt.VK_ENTER){
            BairroCliente.requestFocus();
        }
    }//GEN-LAST:event_CEPClienteKeyPressed

    private void TelefoneClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TelefoneClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TelefoneClienteActionPerformed

    private void TelefoneClienteKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TelefoneClienteKeyPressed
        // TODO add your handling code here:
        if(evt.getExtendedKeyCode() == evt.VK_ENTER){
            CEPCliente.requestFocus();
        }
    }//GEN-LAST:event_TelefoneClienteKeyPressed

    private void CidadeClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CidadeClienteActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_CidadeClienteActionPerformed

    private void CidadeClienteKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CidadeClienteKeyPressed
        // TODO add your handling code here:
        if(evt.getExtendedKeyCode() == evt.VK_ENTER){
            EnderecoCliente.requestFocus();
        }
    }//GEN-LAST:event_CidadeClienteKeyPressed

    private void CidadeClienteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CidadeClienteKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_CidadeClienteKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField BairroCliente;
    private javax.swing.JLabel BairroClienteLabel;
    private javax.swing.JFormattedTextField CEPCliente;
    private javax.swing.JLabel CEPClienteLabel;
    private javax.swing.JButton CadastrarBtn;
    private javax.swing.JButton CancelarBtn;
    private javax.swing.JTextField CidadeCliente;
    private javax.swing.JLabel CidadeClienteLabel;
    private javax.swing.JTextField EnderecoCliente;
    private javax.swing.JLabel EnderecoClienteLabel;
    private javax.swing.JTextField NomeCliente;
    private javax.swing.JLabel NomeClienteLabel;
    private javax.swing.JTextField NumeroCliente;
    private javax.swing.JLabel NumeroClienteLabel;
    private javax.swing.JFormattedTextField TelefoneCliente;
    private javax.swing.JLabel TelefoneClienteLabel;
    private javax.swing.JLabel UFCLienteLabel;
    private javax.swing.JTextField UFCliente;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
