/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Clientes;

import floricultura.TelaInicial.AddCategoria;
import floricultura.TelaInicial.AddSubCategoria;
import floricultura.entrada_de_produtos;
import floricultura.saida_de_produtos;
/**
 *
 * @author pedro
 */
public class ConsultaClientes extends javax.swing.JFrame {

    /**
     * Creates new form ConsultaClientes
     */
    public ConsultaClientes() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TituloLabel = new javax.swing.JLabel();
        SubCategoria = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        NomeCliente = new javax.swing.JTextField();
        SubCategoria1 = new javax.swing.JLabel();
        SubCategoria2 = new javax.swing.JLabel();
        jMenuBar = new javax.swing.JMenuBar();
        Produtos = new javax.swing.JMenu();
        CadastroProduto = new javax.swing.JMenuItem();
        ConsultaProduto = new javax.swing.JMenuItem();
        Clientes = new javax.swing.JMenu();
        CadastroCliente = new javax.swing.JMenuItem();
        ConsultaClientes = new javax.swing.JMenuItem();
        Vendas = new javax.swing.JMenu();
        ConsultaVendas = new javax.swing.JMenuItem();
        RealizarVenda = new javax.swing.JMenuItem();
        Categoria = new javax.swing.JMenu();
        CategoriasSubmenu = new javax.swing.JMenu();
        CadastroCategoria = new javax.swing.JMenuItem();
        VisualizarCategoria = new javax.swing.JMenuItem();
        SubCategoriasSubmenu = new javax.swing.JMenu();
        CadastroSubCategoria = new javax.swing.JMenuItem();
        VisualizarSubCategoria = new javax.swing.JMenuItem();
        Estoque = new javax.swing.JMenu();
        EntradaProdutos = new javax.swing.JMenuItem();
        SaidaProdutos = new javax.swing.JMenuItem();
        Logs = new javax.swing.JMenu();
        VisualizarLog = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        TituloLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        TituloLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TituloLabel.setText("Consultar Clientes");
        TituloLabel.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);

        SubCategoria.setText("Consulte aqui todos os clientes da loja");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "IdCliente", "Nome Cliente", "Telefone", "CEP", "Endereco", "Bairro", "Numero", "UF"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        NomeCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NomeClienteActionPerformed(evt);
            }
        });

        SubCategoria1.setText("Pesquisar");

        SubCategoria2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Clientes/lupa (2).png"))); // NOI18N

        Produtos.setText("Produtos");

        CadastroProduto.setText("Cadastro de Produto");
        CadastroProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CadastroProdutoActionPerformed(evt);
            }
        });
        Produtos.add(CadastroProduto);

        ConsultaProduto.setText("Consultar Produto");
        Produtos.add(ConsultaProduto);

        jMenuBar.add(Produtos);

        Clientes.setText("Clientes");

        CadastroCliente.setText("Cadastrar Clientes");
        CadastroCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CadastroClienteActionPerformed(evt);
            }
        });
        Clientes.add(CadastroCliente);

        ConsultaClientes.setText("Consultar Clientes");
        Clientes.add(ConsultaClientes);

        jMenuBar.add(Clientes);

        Vendas.setText("Vendas");

        ConsultaVendas.setText("Consultar Vendas");
        Vendas.add(ConsultaVendas);

        RealizarVenda.setText("RealizarVendas");
        Vendas.add(RealizarVenda);

        jMenuBar.add(Vendas);

        Categoria.setText("Categorias");

        CategoriasSubmenu.setText("Categorias");

        CadastroCategoria.setText("Adicionar Categoria");
        CadastroCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CadastroCategoriaActionPerformed(evt);
            }
        });
        CategoriasSubmenu.add(CadastroCategoria);

        VisualizarCategoria.setText("Visualizar Categorias");
        VisualizarCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VisualizarCategoriaActionPerformed(evt);
            }
        });
        CategoriasSubmenu.add(VisualizarCategoria);

        Categoria.add(CategoriasSubmenu);

        SubCategoriasSubmenu.setText("SubCategorias");

        CadastroSubCategoria.setText("Adicionar SubCategoria");
        CadastroSubCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CadastroSubCategoriaActionPerformed(evt);
            }
        });
        SubCategoriasSubmenu.add(CadastroSubCategoria);

        VisualizarSubCategoria.setText("Visualizar SubCategorias");
        VisualizarSubCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VisualizarSubCategoriaActionPerformed(evt);
            }
        });
        SubCategoriasSubmenu.add(VisualizarSubCategoria);

        Categoria.add(SubCategoriasSubmenu);

        jMenuBar.add(Categoria);

        Estoque.setText("Estoque");

        EntradaProdutos.setText("Entrada de Produtos");
        EntradaProdutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EntradaProdutosActionPerformed(evt);
            }
        });
        Estoque.add(EntradaProdutos);

        SaidaProdutos.setText("Saida de Produtos");
        SaidaProdutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaidaProdutosActionPerformed(evt);
            }
        });
        Estoque.add(SaidaProdutos);

        jMenuBar.add(Estoque);

        Logs.setText("Logs");

        VisualizarLog.setText("Visualizar Logs");
        Logs.add(VisualizarLog);

        jMenuBar.add(Logs);

        setJMenuBar(jMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(SubCategoria)
                    .addComponent(TituloLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 92, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(SubCategoria1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(NomeCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(SubCategoria2)))
                .addGap(36, 36, 36))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(TituloLabel)
                    .addComponent(SubCategoria1))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(SubCategoria)
                            .addComponent(NomeCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(SubCategoria2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 301, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CadastroProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CadastroProdutoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CadastroProdutoActionPerformed

    private void CadastroClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CadastroClienteActionPerformed
        // TODO add your handling code here:
        new CadastroCliente().setVisible(true);
    }//GEN-LAST:event_CadastroClienteActionPerformed

    private void CadastroCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CadastroCategoriaActionPerformed
        // TODO add your handling code here:]
        new AddCategoria().setVisible(true);
    }//GEN-LAST:event_CadastroCategoriaActionPerformed

    private void VisualizarCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VisualizarCategoriaActionPerformed
        // TODO add your handling code here:
        new AddCategoria().setVisible(true);
    }//GEN-LAST:event_VisualizarCategoriaActionPerformed

    private void CadastroSubCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CadastroSubCategoriaActionPerformed
        // TODO add your handling code here:
        new AddSubCategoria().setVisible(true);
    }//GEN-LAST:event_CadastroSubCategoriaActionPerformed

    private void VisualizarSubCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VisualizarSubCategoriaActionPerformed
        // TODO add your handling code here:
        new AddSubCategoria().setVisible(true);
    }//GEN-LAST:event_VisualizarSubCategoriaActionPerformed

    private void EntradaProdutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EntradaProdutosActionPerformed
        // TODO add your handling code here:
        new entrada_de_produtos().setVisible(true);
    }//GEN-LAST:event_EntradaProdutosActionPerformed

    private void SaidaProdutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaidaProdutosActionPerformed
        // TODO add your handling code here:
        new saida_de_produtos().setVisible(true);
    }//GEN-LAST:event_SaidaProdutosActionPerformed

    private void NomeClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NomeClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NomeClienteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConsultaClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConsultaClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConsultaClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConsultaClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ConsultaClientes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem CadastroCategoria;
    private javax.swing.JMenuItem CadastroCliente;
    private javax.swing.JMenuItem CadastroProduto;
    private javax.swing.JMenuItem CadastroSubCategoria;
    private javax.swing.JMenu Categoria;
    private javax.swing.JMenu CategoriasSubmenu;
    private javax.swing.JMenu Clientes;
    private javax.swing.JMenuItem ConsultaClientes;
    private javax.swing.JMenuItem ConsultaProduto;
    private javax.swing.JMenuItem ConsultaVendas;
    private javax.swing.JMenuItem EntradaProdutos;
    private javax.swing.JMenu Estoque;
    private javax.swing.JMenu Logs;
    private javax.swing.JTextField NomeCliente;
    private javax.swing.JMenu Produtos;
    private javax.swing.JMenuItem RealizarVenda;
    private javax.swing.JMenuItem SaidaProdutos;
    private javax.swing.JLabel SubCategoria;
    private javax.swing.JLabel SubCategoria1;
    private javax.swing.JLabel SubCategoria2;
    private javax.swing.JMenu SubCategoriasSubmenu;
    private javax.swing.JLabel TituloLabel;
    private javax.swing.JMenu Vendas;
    private javax.swing.JMenuItem VisualizarCategoria;
    private javax.swing.JMenuItem VisualizarLog;
    private javax.swing.JMenuItem VisualizarSubCategoria;
    private javax.swing.JMenuBar jMenuBar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
