/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package floricultura.TelaInicial;

import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.Date;
import floricultura.CadastroCliente;
import floricultura.entrada_de_produtos;
import floricultura.saida_de_produtos;

/**
 *
 * @author pedro
 */
public class TelaInicial extends javax.swing.JFrame {

    /**
     * Creates new form TelaInicial
     */
    public TelaInicial() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jMenuBar = new javax.swing.JMenuBar();
        Produtos = new javax.swing.JMenu();
        CadastroProduto = new javax.swing.JMenuItem();
        ConsultaProduto = new javax.swing.JMenuItem();
        Clientes = new javax.swing.JMenu();
        CadastroCliente = new javax.swing.JMenuItem();
        ConsultaClientes = new javax.swing.JMenuItem();
        Vendas = new javax.swing.JMenu();
        ConsultaVendas = new javax.swing.JMenuItem();
        Categoria = new javax.swing.JMenu();
        CategoriasSubmenu = new javax.swing.JMenu();
        CadastroCategoria = new javax.swing.JMenuItem();
        VisualizarCategoria = new javax.swing.JMenuItem();
        SubCategoriasSubmenu = new javax.swing.JMenu();
        CadastroSubCategoria = new javax.swing.JMenuItem();
        VisualizarSubCategoria = new javax.swing.JMenuItem();
        Estoque = new javax.swing.JMenu();
        EntradaProdutos = new javax.swing.JMenuItem();
        SaidaProdutos = new javax.swing.JMenuItem();
        Logs = new javax.swing.JMenu();
        VisualizarLog = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(45, 45, 45));

        jPanel1.setBackground(new java.awt.Color(45, 45, 45));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(242, 242, 242));
        jLabel3.setText("Sistema Floricultura");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(242, 242, 242));
        jLabel4.setText("Pedro Majewski");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(34, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(32, 32, 32))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(jLabel4)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/floricultura/TelaInicial/fundo.jpg"))); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        Produtos.setText("Produtos");

        CadastroProduto.setText("Cadastro de Produto");
        CadastroProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CadastroProdutoActionPerformed(evt);
            }
        });
        Produtos.add(CadastroProduto);

        ConsultaProduto.setText("Consultar Produto");
        Produtos.add(ConsultaProduto);

        jMenuBar.add(Produtos);

        Clientes.setText("Clientes");

        CadastroCliente.setText("Cadastrar Clientes");
        CadastroCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CadastroClienteActionPerformed(evt);
            }
        });
        Clientes.add(CadastroCliente);

        ConsultaClientes.setText("Consultar Clientes");
        Clientes.add(ConsultaClientes);

        jMenuBar.add(Clientes);

        Vendas.setText("Vendas");

        ConsultaVendas.setText("Consultar Vendas");
        Vendas.add(ConsultaVendas);

        jMenuBar.add(Vendas);

        Categoria.setText("Categorias");

        CategoriasSubmenu.setText("Categorias");

        CadastroCategoria.setText("Adicionar Categoria");
        CategoriasSubmenu.add(CadastroCategoria);

        VisualizarCategoria.setText("Visualizar Categorias");
        CategoriasSubmenu.add(VisualizarCategoria);

        Categoria.add(CategoriasSubmenu);

        SubCategoriasSubmenu.setText("SubCategorias");

        CadastroSubCategoria.setText("Adicionar SubCategoria");
        SubCategoriasSubmenu.add(CadastroSubCategoria);

        VisualizarSubCategoria.setText("Visualizar SubCategorias");
        SubCategoriasSubmenu.add(VisualizarSubCategoria);

        Categoria.add(SubCategoriasSubmenu);

        jMenuBar.add(Categoria);

        Estoque.setText("Estoque");

        EntradaProdutos.setText("Entrada de Produtos");
        EntradaProdutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EntradaProdutosActionPerformed(evt);
            }
        });
        Estoque.add(EntradaProdutos);

        SaidaProdutos.setText("Saida de Produtos");
        SaidaProdutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaidaProdutosActionPerformed(evt);
            }
        });
        Estoque.add(SaidaProdutos);

        jMenuBar.add(Estoque);

        Logs.setText("Logs");

        VisualizarLog.setText("Visualizar Logs");
        Logs.add(VisualizarLog);

        jMenuBar.add(Logs);

        setJMenuBar(jMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CadastroProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CadastroProdutoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CadastroProdutoActionPerformed

    
    private void SaidaProdutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaidaProdutosActionPerformed
        // TODO add your handling code here:
        new saida_de_produtos().setVisible(true);
    }//GEN-LAST:event_SaidaProdutosActionPerformed

    private void CadastroClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CadastroClienteActionPerformed
        // TODO add your handling code here:
        new CadastroCliente().setVisible(true);
    }//GEN-LAST:event_CadastroClienteActionPerformed

    private void EntradaProdutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EntradaProdutosActionPerformed
        // TODO add your handling code here:
        new entrada_de_produtos().setVisible(true);
    }//GEN-LAST:event_EntradaProdutosActionPerformed

    /**
     * @param args the command line arguments
     */
    

    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        
        
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaInicial().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem CadastroCategoria;
    private javax.swing.JMenuItem CadastroCliente;
    private javax.swing.JMenuItem CadastroProduto;
    private javax.swing.JMenuItem CadastroSubCategoria;
    private javax.swing.JMenu Categoria;
    private javax.swing.JMenu CategoriasSubmenu;
    private javax.swing.JMenu Clientes;
    private javax.swing.JMenuItem ConsultaClientes;
    private javax.swing.JMenuItem ConsultaProduto;
    private javax.swing.JMenuItem ConsultaVendas;
    private javax.swing.JMenuItem EntradaProdutos;
    private javax.swing.JMenu Estoque;
    private javax.swing.JMenu Logs;
    private javax.swing.JMenu Produtos;
    private javax.swing.JMenuItem SaidaProdutos;
    private javax.swing.JMenu SubCategoriasSubmenu;
    private javax.swing.JMenu Vendas;
    private javax.swing.JMenuItem VisualizarCategoria;
    private javax.swing.JMenuItem VisualizarLog;
    private javax.swing.JMenuItem VisualizarSubCategoria;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenuBar jMenuBar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables

}
