/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Login;

import java.awt.Color;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import javax.swing.JButton;
import javax.swing.plaf.basic.BasicButtonUI;
import TelaInicial.TelaInicial;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import dao.ConexaoBanco;
import dao.JBDCLogin;
/**
 *
 * @author pedro
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    
     private ConexaoBanco Conexao;
     
    public Login() {
        initComponents();
        JButton [] btns = {BtnLogar};
       for(JButton btn : btns){
           btn.setBackground(new Color(186,47,57));
           btn.setUI(new BasicButtonUI());
           btn.addMouseListener(new MouseListener(){
               @Override
               public void mouseClicked(MouseEvent e){
                   
               }
               @Override
               public void mousePressed(MouseEvent e){
                   
               }
               @Override 
                public void mouseReleased(MouseEvent e){
                   
               }
               @Override
               public void mouseEntered(MouseEvent e){
                    btn.setBackground(new Color(239,86,96));
               }
               @Override
               public void mouseExited(MouseEvent e){
                   btn.setBackground(new Color(186,47,57));
               }
           
           });
           }
       Conexao = new ConexaoBanco();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Titulo1 = new javax.swing.JLabel();
        Separator1 = new javax.swing.JLabel();
        Usuario = new javax.swing.JTextField();
        Separator2 = new javax.swing.JLabel();
        Separator3 = new javax.swing.JLabel();
        BtnLogar = new javax.swing.JButton();
        Titulo2 = new javax.swing.JLabel();
        Password = new javax.swing.JPasswordField();
        DireitaLogin = new javax.swing.JPanel();
        Titulo = new javax.swing.JLabel();
        Separator = new javax.swing.JLabel();
        Separator4 = new javax.swing.JLabel();
        Separator5 = new javax.swing.JLabel();
        Separator6 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        Titulo1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        Titulo1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Titulo1.setText("Olá Usuário!");
        Titulo1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        Separator1.setBackground(new java.awt.Color(0, 0, 0));
        Separator1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Separator1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Separator1.setText("Usuário:");
        Separator1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        Usuario.setBackground(new java.awt.Color(255, 243, 244));
        Usuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UsuarioActionPerformed(evt);
            }
        });
        Usuario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                UsuarioKeyPressed(evt);
            }
        });

        Separator2.setBackground(new java.awt.Color(0, 0, 0));
        Separator2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Separator2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Separator2.setText("Faça seu Login abaixo!");
        Separator2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        Separator3.setBackground(new java.awt.Color(0, 0, 0));
        Separator3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Separator3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Separator3.setText("Senha:");
        Separator3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        BtnLogar.setBackground(new java.awt.Color(218, 58, 68));
        BtnLogar.setForeground(new java.awt.Color(255, 255, 255));
        BtnLogar.setText("Logar");
        BtnLogar.setBorderPainted(false);
        BtnLogar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtnLogar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnLogarActionPerformed(evt);
            }
        });

        Titulo2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        Titulo2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Titulo2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Person_3.png"))); // NOI18N
        Titulo2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        Password.setBackground(new java.awt.Color(255, 243, 244));
        Password.setText("teste123");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Titulo1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(Separator3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(Separator2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(Separator1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(144, Short.MAX_VALUE)
                .addComponent(Usuario, javax.swing.GroupLayout.DEFAULT_SIZE, 202, Short.MAX_VALUE)
                .addContainerGap(144, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BtnLogar, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(164, 164, 164))
            .addComponent(Titulo2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Password, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(88, Short.MAX_VALUE)
                .addComponent(Titulo2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Titulo1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Separator2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(Separator1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Separator3, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(Password, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(BtnLogar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(76, 76, 76))
        );

        DireitaLogin.setBackground(new java.awt.Color(218, 58, 68));
        DireitaLogin.setLayout(null);

        Titulo.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        Titulo.setForeground(new java.awt.Color(255, 255, 255));
        Titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Titulo.setText("Casa da Planta");
        Titulo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        DireitaLogin.add(Titulo);
        Titulo.setBounds(0, 152, 318, 32);

        Separator.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Separator.setForeground(new java.awt.Color(255, 255, 255));
        Separator.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Separator.setText("Sistema Floricultura");
        Separator.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        DireitaLogin.add(Separator);
        Separator.setBounds(0, 190, 318, 26);

        Separator4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Separator4.setForeground(new java.awt.Color(255, 255, 255));
        Separator4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Separator4.setText("Faça seu Login a esquerda,");
        Separator4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        DireitaLogin.add(Separator4);
        Separator4.setBounds(0, 275, 318, 20);

        Separator5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Separator5.setForeground(new java.awt.Color(255, 255, 255));
        Separator5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Separator5.setText("em caso de duvida,");
        Separator5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        DireitaLogin.add(Separator5);
        Separator5.setBounds(0, 295, 318, 20);

        Separator6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Separator6.setForeground(new java.awt.Color(255, 255, 255));
        Separator6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Separator6.setText("entre em contato com o suporte!");
        Separator6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        DireitaLogin.add(Separator6);
        Separator6.setBounds(0, 315, 318, 20);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Flores.png"))); // NOI18N
        DireitaLogin.add(jLabel2);
        jLabel2.setBounds(-60, -30, 490, 600);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(DireitaLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(DireitaLogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void UsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UsuarioActionPerformed

    private void BtnLogarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnLogarActionPerformed
        // TODO add your handling code here:
        String user = Usuario.getText();
        String senha = new String(Password.getPassword()); // Obtendo a senha de forma segura
        validarLogin(user, senha);
        
    }//GEN-LAST:event_BtnLogarActionPerformed

    private void UsuarioKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_UsuarioKeyPressed
        // TODO add your handling code here:
       if(evt.getExtendedKeyCode() == evt.VK_ENTER){
            Password.requestFocus();
        }
    }//GEN-LAST:event_UsuarioKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }
    
    private void validarLogin(String User, String Senha) {

            JBDCLogin AuthLogin = new JBDCLogin();
            Boolean Autenticacao = AuthLogin.AuthRegistro(User, Senha);
            
            if(Autenticacao){ 
                JOptionPane.showMessageDialog(this, "Login bem-sucedido!", "Sucesso", JOptionPane.INFORMATION_MESSAGE);
                TelaInicial telaInicial = new TelaInicial();
                telaInicial.setVisible(true);
                setVisible(false);
                JFrame frame = (JFrame) SwingUtilities.getWindowAncestor(this);
                frame.dispose();
            } else {
        
            }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnLogar;
    private javax.swing.JPanel DireitaLogin;
    private javax.swing.JPasswordField Password;
    private javax.swing.JLabel Separator;
    private javax.swing.JLabel Separator1;
    private javax.swing.JLabel Separator2;
    private javax.swing.JLabel Separator3;
    private javax.swing.JLabel Separator4;
    private javax.swing.JLabel Separator5;
    private javax.swing.JLabel Separator6;
    private javax.swing.JLabel Titulo;
    private javax.swing.JLabel Titulo1;
    private javax.swing.JLabel Titulo2;
    private javax.swing.JTextField Usuario;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
